In [1]:
import numpy as np
import pandas as pd

In [2]:
import crossMatrixFull as cmf

In [3]:
df1 = pd.read_csv('data/dane1.csv',sep=';',index_col=0)
df1.head()

    nazwa  true  predicted
0   kukur     1          1
1  jecz_j     2          6
2   kukur     1          1
3   kukur     1          1
4   owies     3         13

In [4]:
cross = cmf.ConfusionMatrix(df1)

In [5]:
cross.cros

     1  2  3  4  5  6   7  8  9  10  11  12  13  14  15  16  17  18
1   13  0  0  0  0  0   0  0  0   0   0   1   0   0   0   0   0   0
2    0  2  1  1  0  4   2  3  0   0   0   0   2   0   0   0   2   0
3    1  1  0  0  0  2   0  2  0   0   0   2   1   2   4   2   2   0
4    0  0  0  4  1  0   1  0  0   0   1   3   0   2   1   2   1   0
5    0  0  0  0  6  0  11  0  0   0   0   0   0   0   0   0   0   0
6    0  4  2  0  0  0   0  0  0   0   0   0   4   1   1   0   0   0
7    0  0  0  0  6  0  11  1  0   0   0   0   0   0   0   0   0   0
8    0  2  0  2  0  1   0  0  0   1   0   0   1   1   1   1   0   0
9    0  0  0  0  1  0   0  0  9   5   0   0   3   0   0   0   0   0
10   0  0  0  1  2  0   0  0  5   3   0   0   2   0   2   0   2   0
11   2  0  1  2  0  0   0  0  0   0   3   2   0   2   1   0   0   0
12   0  0  0  3  0  0   0  0  0   0   1   5   0   0   1   0   0   0
13   0  0  1  0  1  0   0  0  3   3   0   0   3   0   0   0   0   0
14   0  1  1  0  0  3   0  0  0   0   1   1   0   0   2   0   1   0
15   0  0  0  1  0  0   0  1  0   0   2   0   0   0   1   0   1   3
16   0  0  1  0  0  0   0  0  0   0   0   1   0   2   2   2   2   3
17   0  0  1  0  0  0   0  1  0   0   0   0   0   2   1   1   2   2
18   0  0  1  0  0  1   0  0  0   0   0   0   0   0   1   2   2   4

In [6]:
cross.cros1

predicted,kukur,jecz_j,owies,lubin,rzepak_o,pszen_j,kapu_rzep_o,pszenzyt_j,pszenzyt_o,zyt_o,ziemniak,gryka,pszen_o,zboze_mix,ugor,trawy_1,trawy_2,TUZ
true,,,,,,,,,,,,,,,,,,
kukur,13,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
jecz_j,0,2,1,1,0,4,2,3,0,0,0,0,2,0,0,0,2,0
owies,1,1,0,0,0,2,0,2,0,0,0,2,1,2,4,2,2,0
lubin,0,0,0,4,1,0,1,0,0,0,1,3,0,2,1,2,1,0
rzepak_o,0,0,0,0,6,0,11,0,0,0,0,0,0,0,0,0,0,0
pszen_j,0,4,2,0,0,0,0,0,0,0,0,0,4,1,1,0,0,0
kapu_rzep_o,0,0,0,0,6,0,11,1,0,0,0,0,0,0,0,0,0,0
pszenzyt_j,0,2,0,2,0,1,0,0,0,1,0,0,1,1,1,1,0,0
pszenzyt_o,0,0,0,0,1,0,0,0,9,5,0,0,3,0,0,0,0,0
zyt_o,0,0,0,1,2,0,0,0,5,3,0,0,2,0,2,0,2,0
ziemniak,2,0,1,2,0,0,0,0,0,0,3,2,0,2,1,0,0,0
gryka,0,0,0,3,0,0,0,0,0,0,1,5,0,0,1,0,0,0
pszen_o,0,0,1,0,1,0,0,0,3,3,0,0,3,0,0,0,0,0
zboze_mix,0,1,1,0,0,3,0,0,0,0,1,1,0,0,2,0,1,0
ugor,0,0,0,1,0,0,0,1,0,0,2,0,0,0,1,0,1,3
trawy_1,0,0,1,0,0,0,0,0,0,0,0,1,0,2,2,2,2,3
trawy_2,0,0,1,0,0,0,0,1,0,0,0,0,0,2,1,1,2,2
TUZ,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,2,2,4

In [7]:
cross.labelsMap

{'1': 'kukur',
 '2': 'jecz_j',
 '3': 'owies',
 '4': 'lubin',
 '5': 'rzepak_o',
 '6': 'pszen_j',
 '7': 'kapu_rzep_o',
 '8': 'pszenzyt_j',
 '9': 'pszenzyt_o',
 '10': 'zyt_o',
 '11': 'ziemniak',
 '12': 'gryka',
 '13': 'pszen_o',
 '14': 'zboze_mix',
 '15': 'ugor',
 '16': 'trawy_1',
 '17': 'trawy_2',
 '18': 'TUZ'}

In [8]:
cross.labels

0        kukur
1       jecz_j
2        kukur
3        kukur
4        owies
        ...
240      gryka
241      zyt_o
242    trawy_1
243       ugor
244    trawy_2
Name: nazwa, Length: 245, dtype: object

In [9]:
cross.cros1.columns.to_list()

['kukur',
 'jecz_j',
 'owies',
 'lubin',
 'rzepak_o',
 'pszen_j',
 'kapu_rzep_o',
 'pszenzyt_j',
 'pszenzyt_o',
 'zyt_o',
 'ziemniak',
 'gryka',
 'pszen_o',
 'zboze_mix',
 'ugor',
 'trawy_1',
 'trawy_2',
 'TUZ']

In [10]:
cross.crosFull1

predicted,kukur,jecz_j,owies,lubin,rzepak_o,pszen_j,kapu_rzep_o,pszenzyt_j,pszenzyt_o,zyt_o,ziemniak,gryka,pszen_o,zboze_mix,ugor,trawy_1,trawy_2,TUZ,sumRow
true,,,,,,,,,,,,,,,,,,,
kukur,13,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,14
jecz_j,0,2,1,1,0,4,2,3,0,0,0,0,2,0,0,0,2,0,17
owies,1,1,0,0,0,2,0,2,0,0,0,2,1,2,4,2,2,0,19
lubin,0,0,0,4,1,0,1,0,0,0,1,3,0,2,1,2,1,0,16
rzepak_o,0,0,0,0,6,0,11,0,0,0,0,0,0,0,0,0,0,0,17
pszen_j,0,4,2,0,0,0,0,0,0,0,0,0,4,1,1,0,0,0,12
kapu_rzep_o,0,0,0,0,6,0,11,1,0,0,0,0,0,0,0,0,0,0,18
pszenzyt_j,0,2,0,2,0,1,0,0,0,1,0,0,1,1,1,1,0,0,10
pszenzyt_o,0,0,0,0,1,0,0,0,9,5,0,0,3,0,0,0,0,0,18
zyt_o,0,0,0,1,2,0,0,0,5,3,0,0,2,0,2,0,2,0,17
ziemniak,2,0,1,2,0,0,0,0,0,0,3,2,0,2,1,0,0,0,13
gryka,0,0,0,3,0,0,0,0,0,0,1,5,0,0,1,0,0,0,10
pszen_o,0,0,1,0,1,0,0,0,3,3,0,0,3,0,0,0,0,0,11
zboze_mix,0,1,1,0,0,3,0,0,0,0,1,1,0,0,2,0,1,0,10
ugor,0,0,0,1,0,0,0,1,0,0,2,0,0,0,1,0,1,3,9
trawy_1,0,0,1,0,0,0,0,0,0,0,0,1,0,2,2,2,2,3,13
trawy_2,0,0,1,0,0,0,0,1,0,0,0,0,0,2,1,1,2,2,10
TUZ,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,2,2,4,11
sumCol,16,10,9,14,17,11,25,8,17,12,8,15,16,12,18,10,15,12,245